// build-guest.mjs — assemble the Tier-2 guest program from the SHARED pure core
// (host/{util,reputation-core,protocol,manifest-core}.ts) + the orchestration
// body, so the wire format has ONE definition instead of a hand-copied second one.
//
// The guest is loaded as plain QuickJS *source* (not an ESM module), which
// prepends `APP`/`LOCAL` config blocks — so this emits a FLAT script: strip ESM
// import/export scaffolding off the compiled core, then append the orchestration
// body verbatim. No IIFE, no globalThis assignment.
//
//   node scripts/build-guest.mjs   →  build/host/tier2-guest.js
//
// Run after `npm run build:host` and before `npm run build:host:min`.

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");
const build = join(root, "build", "host");

// Compiled shared core, in dependency order (util before its dependents).
const coreFiles = ["util.js", "reputation-core.js", "protocol.js", "manifest-core.js"].map((f) => join(build, f));
const orchestration = join(root, "host", "tier2-guest.orchestration.js");

for (const f of [...coreFiles, orchestration]) {
  if (!existsSync(f)) {
    console.error(`build-guest: missing ${f} — run \`npm run build:host\` first.`);
    process.exit(1);
  }
}

/** Strip the ESM scaffolding off a compiled module so it can be inlined into a
 *  flat script: drop imports, sourcemap refs, and re-exports (their names are
 *  defined by another bundled file), and un-export top-level declarations. */
function stripModule(src) {
  return src
    .replace(/^\s*import\s[^\n]*$/gm, "")
    .replace(/^\/\/#\s*sourceMappingURL=.*$/gm, "")
    .replace(/^\s*export\s*\{[^}]*\}\s*(?:from\s*['"][^'"]+['"])?\s*;?\s*$/gm, "")
    .replace(/^export\s+(async\s+function|function|class|const|let|var)\b/gm, "$1");
}

let out = "// GENERATED by scripts/build-guest.mjs — edit host/tier2-guest.orchestration.js\n"
  + "// or the shared core (host/{util,reputation-core,protocol,manifest-core}.ts), then rebuild.\n"
  + '"use strict";\n';
for (const f of coreFiles) {
  out += `\n// ===== shared core: ${f.slice(root.length + 1)} =====\n${stripModule(readFileSync(f, "utf8")).trim()}\n`;
}
// The orchestration is already a flat "use strict" script; drop its leading
// directive so the bundle has a single one at the top, then append verbatim.
const orch = readFileSync(orchestration, "utf8").replace(/^\s*"use strict";\s*\n/, "");
out += `\n// ===== orchestration: host/tier2-guest.orchestration.js =====\n${orch}`;

const dest = join(build, "tier2-guest.js");
writeFileSync(dest, out);
console.log(`build-guest: stitched ${coreFiles.length} core module(s) + orchestration → build/host/tier2-guest.js (${out.length} bytes)`);
